[2021-12-13 20:43:03,886] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table manual__2021-12-13T20:43:03.557339+00:00 [queued]>
[2021-12-13 20:43:03,899] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table manual__2021-12-13T20:43:03.557339+00:00 [queued]>
[2021-12-13 20:43:03,899] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 20:43:03,899] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-13 20:43:03,899] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 20:43:03,914] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2021-12-13 20:43:03.557339+00:00
[2021-12-13 20:43:03,919] {standard_task_runner.py:52} INFO - Started process 3694 to run task
[2021-12-13 20:43:03,923] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'manual__2021-12-13T20:43:03.557339+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmpwgnymon_', '--error-file', '/tmp/tmpwgzu9qg_']
[2021-12-13 20:43:03,924] {standard_task_runner.py:77} INFO - Job 17: Subtask create_pet_table
[2021-12-13 20:43:03,968] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table manual__2021-12-13T20:43:03.557339+00:00 [running]> on host ef07609851a1
[2021-12-13 20:43:04,024] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T20:43:03.557339+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-13T20:43:03.557339+00:00
[2021-12-13 20:43:04,034] {base.py:79} INFO - Using connection to: id: postgres_***_db. Host: postgres-***, Port: 5432, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-13 20:43:04,038] {dbapi.py:225} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS pet (
            pet_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            OWNER VARCHAR NOT NULL);
          , parameters: None
[2021-12-13 20:43:04,041] {postgres.py:71} INFO - NOTICE:  relation "pet" already exists, skipping

[2021-12-13 20:43:04,056] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20211213T204303, start_date=20211213T204303, end_date=20211213T204304
[2021-12-13 20:43:04,097] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-13 20:43:04,141] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
